### ISSUE TITLE
Thème ggplot2

### ISSUE THREAD

**Issue by tvroylandt** [spyrales/gouvdown#1]
Faire les éléments de thème pour `ggplot2`

**Comment by MaelTheuliere** [comment]
Ajouter un logo sur un ggplot : https://themockup.netlify.app/posts/2019-01-09-add-a-logo-to-your-plot/

**Comment by tvroylandt** [comment]
Pour le logo, il faudra distinguer deux cas :
+ graph directement dans une publi -> pas de logo ;
+ graph utilisé seul -> logo.

On peut penser à une fonction wrapper comme la BBC avec `finalise_plot()` : https://bbc.github.io/rcookbook/#save_out_your_finished_chart

**Comment by MaelTheuliere** [comment]
On va être confronté à la gestion des palettes pour windows. Si j'ai bien suivi, il faudra pour ggplot un truc complémentaire à base d'extrafont pour importer les polices au chargement du package

**Comment by tvroylandt** [comment]
Ya ça qui peut aider : https://github.com/r-lib/systemfonts

**Comment by MaelTheuliere** [comment]
Super, merci, c'est le complément d'extrafont qui me manquait quand les polices ne sont pas installées dans le path par défaut.

**Comment by tvroylandt** [comment]
Je me demande si faudrait pas un `geom_text` avec une autre police par défaut

**Comment by RLesur** [comment]
Lorsque les polices ne sont pas installées sur le poste, il me semble qu'on peut aussi utiliser [showtext](https://cran.rstudio.com/web/packages/showtext/vignettes/introduction.html).

**Comment by MaelTheuliere** [comment]
J'ai un truc qui marche avec extrafont : 35d24a4

**Comment by RLesur** [comment]
C'est chouette mais êtes-vous sûr que tout le monde a le droit d'installer des polices sur sa machine ? Moi, par exemple, au boulot je ne peux pas... mais on peut espérer que ce sera installé sur tous les postes.

**Comment by MaelTheuliere** [comment]
Même sur ton espace user ? Je faisait l'hypothèse qu'il fallait aussi restreindre l'usage de la font à ceux qui peuvent l'installer...

**Comment by MaelTheuliere** [comment]
ça vous semble ok ? 
![image](https://user-images.githubusercontent.com/2116892/80566169-a154c680-89f2-11ea-98be-f0599887bfa1.png)

**Comment by MaelTheuliere** [comment]
obligé de mettre un fond un peu sombre pour la palette principale

**Comment by tvroylandt** [comment]
C'est super !

J'avoue que si on pouvait se passer du fond sombre (et donc de la palette FR de fait, ou au moins du blanc), je préfère.

**Comment by MaelTheuliere** [comment]
moi aussi ;-)

**Comment by MaelTheuliere** [comment]
on peut faire une version light qui serait celle par défaut, une version regular comme celle là

**Comment by tvroylandt** [comment]
De fait la palette par défaut dans `ggplot2`, c'est la A (la marron). Donc sur un fond blanc, elle passe.
On pourrait mettre en défault la palette `pal_gouv_qual1` qui reprend simplement tous les niveaux proposés et qui de fait va avec un thème blanc.

**Comment by MaelTheuliere** [comment]
Ca marche. Si je récapitule :

- [ ] `theme_gouv()` avec tous les paramètres possible à changer, en version light par défaut
- [ ] `theme_gouv_grey()` version fond gris de `theme_gouv()` pour des graphiques en bbr
- [ ] `theme_gouv_map()` pour les cartes (process un peu spécifique sur les axes et les grids)
- [ ] `add_bloque_marque()` pour ajouter le logo, basé sur [bbplot]( https://github.com/bbc/bbplot/blob/82af5952230c695bd317d7786587cfffea7f7621/R/finalise_plot.R#L18-L71)

Et une modif de la palette par défaut là dessus pour être cohérent avec le theme light
Si ça vous va je dois pouvoir boucler ça aujourd'hui.

**Comment by MaelTheuliere** [comment]
Une dernière question : j'ai ajouté le paramètre `plot.title.position` qui n'est disponible que dans la dernière version de ggplot2, ça demande à modifier les dépendances pour forcer les utilisateurs à mettre à jour. Je pense que ça vaut le coup, mais qu'en pensez vous ?

**Comment by tvroylandt** [comment]
Je suis d'accord avec tout.

Pour `plot.title.position` aussi. 

J'allais même suggérer de passer en `element_markdown()`avec `ggtext` pour forcer aux bonnes pratiques de design de graph, mais ça rajoute une dépendance pour un truc un peu complexe en utilisation standard. On mettra plutôt ces bonnes pratiques dans le cookbook.

**Comment by RLesur** [comment]
> Même sur ton espace user ?

Je n'ai pas poussé les essais très loin : je ne fais que tu HTML et j'ai décidé de tout déclarer en font face. Mais effectivement, je n'ai pas investi le sujet des graphiques.

Sur les autres sujets, je ne suis vraiment pas expert en graphique. Voici mon avis sur les différents points, pour ce que ça vaut : 

- je vote pour que le thème par défaut soit sur fond blanc avec `pal_gouv_qual1`
- ça ne me choque pas d'avoir la dernière version de ggplot2 comme version requise

**Comment by MaelTheuliere** [comment]
![image](https://user-images.githubusercontent.com/2116892/80607267-996a4600-8a35-11ea-90be-bcc5e841e225.png)

**Comment by tvroylandt** [comment]
C'est beau =)

**Comment by RLesur** [comment]
J'aime beaucoup également !

**Comment by MaelTheuliere** [comment]
J'ai pris un peu de retard, mais c'est bon. Ce sera au propre demain ;-)

![image](https://user-images.githubusercontent.com/2116892/80653070-96914480-8a79-11ea-9223-971eefa2c174.png)

**Comment by RLesur** [comment]
Vous avez vu ça ? Ça commence à peine mais ça me semble prometteur https://rstudio.github.io/thematic/

**Comment by MaelTheuliere** [comment]
oui j'ai vu passé ça ce matin dans ma veille
Je me disais qu'il y avait un soucis pour les palettes qui sont définie de façon stricte en non par rapport à une couleur principale

**Comment by MaelTheuliere** [comment]
Au passage, j'ai un soucis avec `gouvdown-imports.Rd` qui me bloque pour l'utilisation du pipe dans les fonctions. J'ai l'habitude d'utiliser `usethis::use_pipe()` mais là évidemment les deux sont en conflits. Une idée ? Sachant que j'ai pas trouvé où était créé ce `gouvdown-imports.Rd`

**Comment by tvroylandt** [comment]
Oui, j'ai vu. C'est top. Après je connais pas grand monde qui utilise encore `lattice` et `base` pour les graphs. C'est bien quand on a de l'ancienneté et qu'on a commencé avec ça, mais tout le monde fait du `ggplot2` maintenant et ceux qui apprennent maintenant apprennent comme ça. J'en faisais avant mais là je saurai même pas te faire un graph en base .

**Comment by RLesur** [comment]
> Au passage, j'ai un soucis avec `gouvdown-imports.Rd` qui me bloque pour l'utilisation du pipe dans les fonctions. J'ai l'habitude d'utiliser `usethis::use_pipe()` mais là évidemment les deux sont en conflits. Une idée ? Sachant que j'ai pas trouvé où était créé ce `gouvdown-imports.Rd`

Je pense que le mieux serait de discuter de ce sujet dans une pull request : je vais l'ouvrir en WIP.
