### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by tvroylandt** [spyrales/gouvdown#17]
Pour la communication, j'ouvre une issue à part.

Je propose un teasing sur spyrales (sur tchap, la team github et twitter) avec quelques graphs bien beaux, si possible à partir de données réelles. Un truc bien simple genre les mariages ou les naissances ?

Quelques possibilités : 

+ barplot ;
+ scatterplot ;
+ line chart ;
+ une carte.

Ca vous va ?

**Comment by MaelTheuliere** [comment]
Covid?

**Comment by MaelTheuliere** [comment]
Refaire la carte des départements rouge verte et un graphique temporel

**Comment by RLesur** [comment]
Moi ça me va. @strainel , tu en penses quoi ?

**Comment by tvroylandt** [comment]
> Covid?

Si vous voulez. Mais j'avoue que je suis pas fan de prendre le risque de faire quelque chose avec les logos et la charte officielle sur une sujet aussi brûlant.

**Comment by RLesur** [comment]
> > Covid?
> 
> Si vous voulez. Mais j'avoue que je suis pas fan de prendre le risque de faire quelque chose avec les logos et la charte officielle sur une sujet aussi brûlant.

Sage remarque. C'est vrai que l'utilisation de la charte officielle peut engendrer de la confusion...

**Comment by MaelTheuliere** [comment]
Il faut un bas de page qui explique la chose

**Comment by MaelTheuliere** [comment]
Quelques soit le sujet

**Comment by MaelTheuliere** [comment]
Voir même un bandeau latéral avec "document factice" ?

**Comment by strainel** [comment]
S'il faut choisir un thème lié à l'actualité COVID, je proposerai plutôt un thème impacté par la crise : celui de l'économie, avec le nombre de création d'entreprises par exemple. J'imagine que le niveau de création est assez bas, donc il y a un message à la fois intéressant, sans interférence et nouveau (rien vu sur ce sujet ces derniers jours, mais ca m'a peut-être échappé).

**Comment by tvroylandt** [comment]
Ya ça  https://www.insee.fr/fr/statistiques/4477794 mais ya pas de quoi faire une carte (sinon pour les autres graphs c'est top);

Par contre pas moyen de trouver un fichier par région / département propre même peu détaillé, pour faire une carte. Ca doit exister quelque part dans les tréfonds du site de l'Insee.

**Comment by MaelTheuliere** [comment]
normalement en sdmx tu as tout ce qu'il faut. Faut que je retrouve ça..

**Comment by MaelTheuliere** [comment]
(Avec un package pour y accéder directement au passage : https://cran.r-project.org/web/packages/rsdmx/vignettes/quickstart.html)

**Comment by MaelTheuliere** [comment]
hop : https://gist.github.com/MaelTheuliere/9a0460baa160a7287911aef497693ceb

**Comment by MaelTheuliere** [comment]
On met ça dans une vignette ? ça sera toujours ça de fait...

**Comment by MaelTheuliere** [comment]
Oups, je n'avais pas vu, mais les données publiées via le flux  sdmx ne sont que trimestrielles, c'est moins parlant...

**Comment by MaelTheuliere** [comment]
D'autres idées de data ?
On peut aussi se dire qu'on reste sur un exemple national pour l'instant...

**Comment by strainel** [comment]
les données de naissance ?? doit bien y avoir au moins une série chronologique à la maille département...

**Comment by tvroylandt** [comment]
J'ai des séries sur les mariages propres. Je vous fais les graphs dans la semaine.

**Comment by MaelTheuliere** [comment]
Merci @tvroylandt . Sinon j'ai eu le bon lien via la DR insee pour les données départementales : https://www.insee.fr/fr/statistiques/series/102722714
mais c'est tout à la main !

**Comment by tvroylandt** [comment]
Quelques réalisations :

![nb_mariages](https://user-images.githubusercontent.com/28248895/82749735-8ab04e00-9dab-11ea-9ada-36e2b94f20ab.png)
![nb_mariages_dep](https://user-images.githubusercontent.com/28248895/82749737-94d24c80-9dab-11ea-8d47-8b5879939210.png)
![nb_mariages_type](https://user-images.githubusercontent.com/28248895/82749738-969c1000-9dab-11ea-8225-49090680cc10.png)
![nb_mariages](https://user-images.githubusercontent.com/28248895/82749739-98fe6a00-9dab-11ea-99bb-17e459a872a3.png)

Je vais mettre le code dans une vignette

**Comment by tvroylandt** [comment]
J'ai commencé une vignette là : https://github.com/spyrales/gouvdown/commit/ebf1b7e0e4a965f5f83451fb2bfa60a521d26aa5

**Comment by MaelTheuliere** [comment]
Merci @tvroylandt  § Je trouve ça super. Je proposerais bien pour illustrer la force d'avoir un charte pour l'ensemble de l'Etat un graph national avec la marianne ou le bloc marque "République Française" et un graph régional avec le bloc marque de la pref par exemple. J'ai tous les blocs marques des prefs donc je peux les intégrer au package. Je pense toutefois qu'il serait souhaitable de limiter pour l'instant le nombre afin de montrer à voir ce que ça peut donner et permettre de discuter de la meilleure façon de gérer la stockage de ceux ci. Qu'en pensez vous ?

**Comment by tvroylandt** [comment]
Ca peut être une bonne idée oui. On peut faire un des graphs uniquement sur Pays de la Loire avec le bloc-marque de la préfecture.

**Comment by MaelTheuliere** [comment]
Je tente de te proposer un truc ce soir dans la branche

**Comment by MaelTheuliere** [comment]
c'est fait ici : 7c33ebd28339ac4a3e7365e519e3090dff39dd1b

**Comment by tvroylandt** [comment]
Top

**Comment by MaelTheuliere** [comment]
Du coup c'est bon pour une PR non ?
On rajoute une boucle github action pour le pkgdown tant qu'à faire ?
Vous en pensez quoi @tvroylandt @RLesur

**Comment by tvroylandt** [comment]
Ca me va. Je la lance et vous faites la review ?

**Comment by MaelTheuliere** [comment]
Je te rajoute ça dans la branche ?

**Comment by MaelTheuliere** [comment]
fait ! 
je t'ai mis le workflow `usethis ` dans le message de commit pour ton info pour déployer un pkgdown

**Comment by tvroylandt** [comment]
C'est effectivement pas bien violent. Merci !

**Comment by MaelTheuliere** [comment]
non ;-)

**Comment by MaelTheuliere** [comment]
@tvroylandt j'ai rajouté quelques fix sur le dernier commit

**Comment by tvroylandt** [comment]
Mais où trouves tu le temps de faire tout ça ?

**Comment by tvroylandt** [comment]
La PR est faite. 

Qui a le compte Twitter ? Il pourrait poster les graphs une fois mergé ?
