### ISSUE TITLE
collecter tous les bloques marque

### ISSUE THREAD

**Issue by MaelTheuliere** [spyrales/gouvdown#2]
Chaque ministère, préfecture, institut a un bloque marque spécifique. L'idée est de s'assurer qu'ils soient de façon exhaustive stockés à un endroit unique

**Comment by MaelTheuliere** [comment]
Pour recenser ces bloquues marques, plusieurs alterantives :

**Comment by tvroylandt** [comment]
Les blocs-marques sont standardisés non ? On pourrait pas le générer ?

**Comment by MaelTheuliere** [comment]
La standardisation te donne des principes à suivre, par une formule pour te donner clef en main le logo, par exemple comment gérer les saut de page sur cet exemple : https://www.education.gouv.fr/ ? On a récupéré de notre coté tous les fichiers images correspondant au sein de notre ministère, ainsi que ceux des préfectures. J'imagine que c'est le cas ailleurs. Autant partir de cette base là non ?

**Comment by tvroylandt** [comment]
Effectivement tu as raison

**Comment by RLesur** [comment]
Initialement, sans trop y avoir réfléchi, j'étais parti sur la même idée que @tvroylandt, à savoir les générer à la volée.

Cependant, il est exact que chaque fonctionnaire aura probablement à sa disposition sous forme de fichier le bloc-marque de son administration. Je me demande si on ne pourrait pas commencer par quelque chose de très très simple à savoir avoir un argument qui admette un fichier local (ou une url) comprenant le bloc-marque à utiliser.

Si on partait de cette hypothèse (chaque utilisateur possède déjà le bloc-marque qu'il doit utiliser), le besoin d'avoir un mécanisme qui centralise et serve les fichiers de bloc-marque (dans un package ou sur un serveur) serait peut-être moins urgent.

**Comment by MaelTheuliere** [comment]
C'est toujours une manip en plus potentiellement inutile si l'info est bien centralisée quelques part. sans parler des risques de dégradation des fichiers image avec le temps et les bricolages des uns et des autres. Je check auprès de beta.gouv si la chose n'est pas déjàj en route ? Sinon via une opération de crowdsourcing ça peut aller vite... On peut aussi remettre ça à plus tard et facilier le crowdsourcing via un système type geofacet pour ajouter et partager les marques une fois le truc opérationnel : https://hafen.github.io/geofacet/

**Comment by tvroylandt** [comment]
J'ai déjà soumis un truc dans ce repo c'est bien comme système.

Après on va se retrouver là aussi avec des formats différents non ?  Donc l'option centralisatrice est bien au début si on en récupère 200 d'un coup. 

Et si il en manque, on ajoutera une option mettre son fichier ensuite ?

**Comment by RLesur** [comment]
Je pense qu'il faut laisser toutes les possibilités à l'utilisateur. Et si effectivement, il y a moyen de tout récupérer et d'offir le bon bloc marque de façon simple, ce sera chouette. 

Si on part sur l'idée d'une centralisation des bloc marques, il faudra simplement prévoir une maintenance à chaque remaniement :sweat_smile:

**Comment by tvroylandt** [comment]
De toute façon, faudra bien une instance responsable. Genre un organisme qui s'occupe de stat publique et qui a une sorte d'autorité morale pour les utilisateurs de R dans ce domaine ?

**Comment by RLesur** [comment]
Quand on voit l'avis de l'ASP sur l'usage de la charte graphique gouvernementale pour la stat publique, il y a peu de chance que cette charte graphique soit utilisée telle quelle pour faire de la stat publique :wink:

**Comment by MaelTheuliere** [comment]
> Quand on voit l'avis de l'ASP sur l'usage de la charte graphique gouvernementale pour la stat publique, il y a peu de chance que cette charte graphique soit utilisée telle quelle pour faire de la stat publique wink

Tu as le lien ?

**Comment by tvroylandt** [comment]
https://www.autorite-statistique-publique.fr/delibere-asp-sur-les-publications-statistiques/

**Comment by MaelTheuliere** [comment]
mais c'est pas vrai...
