### ISSUE TITLE
Ajout d'un template bookdown

### ISSUE THREAD

**Issue by MaelTheuliere** [spyrales/gouvdown#26]
Ajout d'un template bookdown marque Etat

**Comment by MaelTheuliere** [comment]
Qu'en pensez vous ?

![Capture d’écran de 2020-09-18 11-19-16](https://user-images.githubusercontent.com/2116892/93581153-0bb9d380-f9a1-11ea-9204-3fc4e54bbaa3.png)

Alternative : mettre le logo en dessous du sommaire...
![Capture d’écran de 2020-09-18 11-26-20](https://user-images.githubusercontent.com/2116892/93581741-da8dd300-f9a1-11ea-8094-1794d00e48ad.png)

J'ai aussi une version fond bleu mais plus compliqué pour le bloque marque :

![Capture d’écran de 2020-09-18 11-23-11](https://user-images.githubusercontent.com/2116892/93581429-710dc480-f9a1-11ea-89b5-6de080bec2f1.png)

**Comment by tvroylandt** [comment]
Top ! Je préféère le logo fond blanc en haut

**Comment by MaelTheuliere** [comment]
@tvroylandt @RLesur dernier point sur gitbook gouv, J'ai besoin de  plusieurs fonctions internes de bookdown. On est d'accord que dans ce cas je les recréé dans gouvdown ?

**Comment by tvroylandt** [comment]
Oui

**Comment by MaelTheuliere** [comment]
ça veut dire par exemple rajouter aussi tout ça dans gouvdown : 
- https://github.com/rstudio/bookdown/tree/master/inst/resources/gitbook
- https://github.com/rstudio/bookdown/tree/master/inst/templates

**Comment by MaelTheuliere** [comment]
Et tracer les modifs faites ensuite sur bookdown pour être à jour ?

**Comment by tvroylandt** [comment]
On a pas tellement le choix de toute façon non ? Puisque si c'est de l'internal c'est pas exporté ? 

Ou alors il y a un moyen que je ne connais pas

**Comment by MaelTheuliere** [comment]
En fait l'idéal serait que bookdown intègre une paramétrisation dans gitbook sur la sortie utilisée => https://github.com/rstudio/bookdown/blob/master/R/gitbook.R#L29
On est obligé de tout dupliquer pour pouvoir remplacer à cet endroit `html_document()` par `html_gouv()`. T'en penses quoi toi @RLesur ?

**Comment by MaelTheuliere** [comment]
honnêtement, ça demande quasiment à réimporter la moitiée de bookdown, je vous propose donc de faire une entorse aux bonnes pratiques en appelant les fonctions non exportées de bookdown pour avancer et de travailler à rendre bookdown plus paramétrable. Je vois deux possibilités :
