### ISSUE TITLE
Echelle de couleurs

### ISSUE THREAD

**Issue by tvroylandt** [spyrales/gouvdown#3]
Construire quatre échelles de couleurs :

+ continue graduée (en bleu ou en rouge) ;
+ continue divergente (passage par 0) ;
+ discrète ordonnée (adaptation de la première échelle) ;
+ discrète pour les groupes.

Et implémenter dans `ggplot2`.

**Comment by tvroylandt** [comment]
Chose intéressante qui n'y était pas (il me semble) au départ, des échelles de couleurs sont déjà proposées : https://www.gouvernement.fr/charte/charte-graphique-les-fondamentaux/les-couleurs

A voir comment on peut s'en servir pour les associer.

**Comment by tvroylandt** [comment]
Les codes (je les recopie car dans l'image c'est pas fou) :

+ 958B62
+ 91AE4F
+ 169B62
+ 466964
+ 00AC8C
+ 5770BE
+ 484D7A
+ FF8D7E
+ D08A77
+ FFC29E
+ FFE800
+ FDCF41
+ FF9940
+ E18B63
+ FF6F4C
+ 7D4E5B
+ A26859
+ 000000

**Comment by MaelTheuliere** [comment]
super, bravo @tvroylandt pour la trouvaille, en effet elles n'y étaient pas au départ

**Comment by tvroylandt** [comment]
La difficulté (je suis dessus là), c'est de bien modifier les paramètres pour arriver sur les bonnes teintes.

Mais aussi d'être un peu propre en associant les couleurs pour pas se retrouver avec un arc-en-ciel mais quand même avoir quelque chose de bien.

Et quid de la place des bleus et rouges principaux dans les graphs ? Ca me parait étrange par exemple d'utiliser une échelle continue (non divergente) ou discrète ordonnée dans une autre gamme que celles définies par ces deux-là... Si on prend un autre rouge, ça va faire  bizarre je trouve.

**Comment by tvroylandt** [comment]
Pour résumer, les couleurs c'est surtout beaucoup de tests. Je vais définir les palettes et on ajustera au feeling et en fonction des colorspace, etc...

**Comment by tvroylandt** [comment]
Bon j'ai réussi à choper toutes les teintes :
