### ISSUE TITLE
Error - "famille de police introuvable dans la base de données des polices Windows"

### ISSUE THREAD

**Issue by clbelliard** [spyrales/gouvdown#42]
Bonjour, 

J'utilise régulièrement le package `gouvdown` mais j'ai systématiquement un problème avec les polices du `theme_gouv()` quand j'utilise `ggplot2`. 

```r
library(dplyr)
library(gouvdown)
library(ggplot2)

n <- 1000
df <- data.frame( id=1:n,
                  x=rnorm(n))


df %>% ggplot(aes(x = x)) +
  geom_histogram(binwidth = 0.02) +
  labs(
    title = "Titre pour exemple", 
    subtitle = "Avec un sous-titre", 
    caption = "Source : rnorm()") +
  theme_gouv()

```

Le plot s'affiche sans les polices Marianne ou Spectral et on me retourne une erreur "famille de police introuvable dans la base de données des polices Windows". 

Les polices sont bien installées sur ma machine. D'ailleurs quand je knit un rmarkdown avec le template "gouvdown html document", les polices s'affichent bien (sauf sur les plots). 

Avez-vous une idée de l'origine de cette erreur ? 

Bien cordialement,

**Comment by MaelTheuliere** [comment]
Bonjour Clément, le package ne permet d'identifier les polices qu'au format ttf. Est ce que tes polices ne seraient pas en otf ? cf ici 
https://github.com/spyrales/gouvdown/issues/41

**Comment by clbelliard** [comment]
Bonjour @MaelTheuliere , effectivement elles sont bien installées en .ttf dont `C:\\WINDOWS\\Fonts`. Elles l'étaient en .otf hier, je les ai supprimé et installé en .tff pensant régler le problème.

```
> systemfonts::match_font("Marianne")$path
[1] "C:\\WINDOWS\\Fonts\\arial.ttf"
> systemfonts::match_font("Spectrale")$path
[1] "C:\\WINDOWS\\Fonts\\arial.ttf"
```
j'ai essayé d'exécuter le script de l'issue 1 de `gouvdown_font` mais il semblerait que je n'ai pas les accès nécessaire à son exécution.

**Comment by MaelTheuliere** [comment]
As tu bien relancé R ensuite ?

**Comment by clbelliard** [comment]
Effectivement, j'étais sur la même session ... En relançant, même problème en utilisant `extrafont::font_import()` mais le [script ici](https://github.com/spyrales/gouvdown.fonts/issues/1) a fonctionné. C'est réglé pour moi, merci beaucoup !
