### ISSUE TITLE
maj logo Préfète de région Centre-Val de Loire

### ISSUE THREAD

**Issue by MurielleDelmotte** [spyrales/gouvdown#46]
Le bloc marque pour la région Centre-Val de Loire n'est plus à jour dans gouvdown.
Il s'agit d'une Préfète et non plus d'un Préfet
Je peux éventuellement vous le transmettre. Reste à savoir le format exact nécessaire. (en RVB, CMJN, ?)
Merci d'avance

**Comment by MaelTheuliere** [comment]
C'est du RVB en png @MurielleL , tu peux faire une PR en modifiant le fichier qui est ici : https://github.com/spyrales/gouvdown/tree/master/inst/resources/blocs_marque/prefecture_r24
