### ISSUE TITLE
git workflow

### ISSUE THREAD

**Issue by MaelTheuliere** [spyrales/gouvdown#8]
On se met d'accord sur un git workflow pour pas se marcher dessus ? une branche par fonctionnalité et une PR pour valider l'ajout ? Je vous soumet un truc pour le thème ce soir

**Comment by RLesur** [comment]
Effectivement, j'ai un peu trop poussé sur master. Personnellement, le [github flow](https://guides.github.com/introduction/flow/) m'irait bien et j'ai l'impression que c'est ce que tu suggérais.

**Comment by RLesur** [comment]
@MaelTheuliere tu fais ça en ajoutant un fichier `CONTRIBUTING.md` ?

**Comment by tvroylandt** [comment]
Ca me va. J'avoue que j'ai pas encore trop le pli de ça, mais ça permet d'apprendre
